In [1]:
# Step 1: Import Required Libraries
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import Binarizer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 2: Load the Iris Dataset
iris = load_iris()
X = iris.data
y = iris.target

# Step 3: Binarize the Data (since BernoulliNB expects binary features)
binarizer = Binarizer(threshold=np.mean(X))  # You can adjust the threshold
X_binarized = binarizer.fit_transform(X)

# Step 4: Split into Train and Test Sets
X_train, X_test, y_train, y_test = train_test_split(X_binarized, y, test_size=0.2, random_state=42)

# Step 5: Train the Bernoulli Naive Bayes Classifier
bnb = BernoulliNB()
bnb.fit(X_train, y_train)

# Step 6: Predict
y_pred = bnb.predict(X_test)

# Step 7: Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.6666666666666666
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.47      1.00      0.64         9
           2       1.00      0.09      0.17        11

    accuracy                           0.67        30
   macro avg       0.82      0.70      0.60        30
weighted avg       0.84      0.67      0.59        30

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0 10  1]]
